# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.20', '5.24', '5.26', '5.28', '5.30', '5.32', 'latest' ]
        threaded: [true, false]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }} (threaded ${{ matrix.threaded }} )
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          multi-thread: ${{ matrix.threaded }}
      - run: sudo apt-get install -y libxml2-dev cpanminus
      - run: sudo cpanm ExtUtils::MakeMaker Module::Build Dist::Zilla
      - run: perl -V
      - run: dzil authordeps --missing | sudo cpanm --notest
      - run: dzil listdeps --author --missing | sudo cpanm --notest
      - run: dzil test --author --release
      - run: sudo cpanm --installdeps .
      - run: prove -lv t

